### ISSUE TITLE
submit job to cluster by yarn

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#923] opened 2017-07-13 11:39 UTC
I have created MyApp project in machine named **hadoop36.bs.ppcredit.com** by command "smv-init -s MyApp", then submit it to cluster by command "smv-pyrun  --run-app -- --master yarn-client --queue ml",throw out below exception, because it will create directory file:/home/ml/workspaces/MyApp/data/output/ in one machine of my cluster while it does not exist, how to resolve it( I can not make directory in every machine of company's cluster), tks

: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 19, **hadoop35.bs.ppcredit.com**, executor 1): java.io.IOException: Mkdirs failed to create file:/home/ml/workspaces/MyApp/data/output/stage1.employment.Employment_23ba3388.meta/_temporary/0/_temporary/attempt_20170713193040_0002_m_000000_19 (exists=false, cwd=file:/data/3/yarn/nm/usercache/ml/appcache/application_1497244969498_61416/container_e17_1497244969498_61416_01_000002)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:442)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:428)

**Comment by AliTajeldin** [comment] 2017-07-18 06:29
Sorry for the delay in response.  I mistakenly thought I had already answered this.

When running on a cluster, you must set your data directory to a directory on HDFS.  This can be done by modifying the `smv.dataDir` configuration parameter in the `conf/smv-user-conf.props`.  For example:
```
smv.dataDir = hdfs://namenode.com:8020/user/me/data
```

You can then put the input files in `hdfs://namenode.com:8020/user/me/data/input` and the output files will go into `hdfs://namenode.com:8020/user/me/data/output`.

Note, the input/output directories can be overriden individually using the `smv.inputDir` and `smv.outputDir` configuration parameters respectively (See https://github.com/TresAmigosSD/SMV/blob/master/docs/user/app_config.md#smv-config-parameters for details)

**Comment by findmaven** [comment] 2017-07-18 09:56
thanks,  will smv support python3 in the future?

**Comment by jimmycheng603** [comment] 2017-07-18 09:57
thanks, will smv support python3 in the future?

**Comment by AliTajeldin** [comment] 2017-07-18 18:19
Yes. absolutely.  We are already testing against python 3.5.2, but we have not made an official announcement yet.

**Comment by jimmycheng603** [comment] 2017-07-21 10:02
I hava initialized a project by "smv-init -s MyApp", then add the tablename() at the end as below,then I execute it in jupyter df('test.employment_tohivetable.MyModule',forceRun=True),it does not create table "tdl.cb1200cz11_bak" in hive, but when I execute by "smv-pyrun -m test.employment_tohivetable.MyModule **--publish-hive**", it works. what is the equivalent method of --publish-hive in jupyter?

class EmploymentByState(SmvModule, SmvOutput):
    """Python ETL Example: employ by state"""
    def requiresDS(self):
        return [Employment]
    def run(self, i):
        df = i[Employment]
        return df.groupBy(col("ST")).agg(sum(col("EMP")).alias("EMP"))
    def tableName(self): return "tdl.cb1200cz11_bak"

**Comment by AliTajeldin** [comment] 2017-07-21 17:25
@jimmycheng603 : we don't expose the equivalent of `--publish-hive` to shell now.  I opened a new ticket to add that functionality (#931)

**Comment by jimmycheng603** [comment] 2017-07-22 15:32
I have set `c.NotebookApp.notebook_dir = u'/home/jimmy/workspaces/MyApp'` in .jupyter/.jupyter/jupyter_notebook_config.py, then I run smv-jupyter from the root of project MyApp(created by smv-init -s MyApp). 
When I open the notebook under the root of MyApp(MyApp/Untitled.ipynb), ls() is ok and everything is ok. but when I open the notebook under the directory of notebooks(MyApp/notebooks/Untitled.ipynb), ls() is not work. Can you tell me how I can execute ls() in the file of "MyApp/notebooks/Untitled.ipynb" normally?(I think notebooks should be default in the directory of notebooks created by smv-init)

**Comment by AliTajeldin** [comment] 2017-07-24 07:11
Just to confirm, by `ls()`, you mean the smv shell `ls()` command?
Just out of curiosity, if your notebook is in `notebooks` directory, why not just keep the `notebook_dir` set to `notebooks`?  Is the problem you are trying to solve is to have multiple notebook directories, or a hierarchy of notebook directories?
We will try to reproduce the problem here.

**Comment by jimmycheng603** [comment] 2017-07-24 14:37
thanks for your reply!
yes, I mean ls() is the command in smv-jupyter. 
If I keep the notebook_dir set to the directory of notebooks, I should start smv-jupyter under it, everything is ok.
I think it is better to set  the notebook_dir to the root of project and start smv-jupyter under the root, but I can code within the jupyter at every place in the project  including under the root of project or under the directory of notebooks.
It should be  further discussed.

**Comment by laneb** [comment] 2017-07-25 22:51
Have you set `c.FileContentsManager.root_dir = u'notebooks'` in your config? If you do this, you _should_ be able to run `smv-jupyter` from the root and develop notebooks in the `notebooks` directory. You shouldn't need to set that `notebook_dir` property either.

**Comment by laneb** [comment] 2017-07-25 23:15
Do you have `c.FileContentsManager.root_dir = u'notebooks'`? If you have this then you should be able to run `smv-jupyter` from the root and develop notebooks in the `notebooks` dir. You wouldn't have to set `c.NotebookApp.notebook_dir` either. Is that sufficient or are you trying to run notebooks from another directory in your project?

By the way, if you run `smv-jupyter` from inside the `notebooks` dir you may be able to run `ls` but you won't get the right results - it will report no modules because there are no modules in the current dir.

**Comment by ninjapapa** [comment] 2017-07-26 02:27
SMV-Jupiter command basically run Jupiter with some init script to start SMV. Since SMV internally assumes that the command run under the project dir (MyApp), we have to run SMV-Jupiter command under the project dir. However, Jupiter allow user to specify a notebook dir, which will be used as the root of all notebooks. I believe we made the notebooks dir under the project dir as the  default notebook root. I'm not sure whether user can specify their own notebook root.

**Comment by AliTajeldin** [comment] 2017-07-26 06:31
Note that there are two configuration parameters at play here: `c.NotebookApp.notebook_dir` and `c.FileContentsManager.root_dir`.  We recommend starting `smv-jupyter` from top of project directory and setting `root_dir`, **not** `notebook_dir` to the root of your notebooks directory.

**Comment by jimmycheng603** [comment] 2017-07-26 15:06
I see, thanks for all of your replies above. 
In addition, I have already open smv-jupyter under the root of project, can I switch to other project? if not, 
does it mean every smv-jupyter for every project?

**Comment by laneb** [comment] 2017-07-26 20:26
You cannot switch a running instance of smv-jupyter to a different project.
You will need to relaunch smv-jupyter at the root of the other project. I
don't understand your second question.

**Comment by ninjapapa** [comment] 2017-07-26 21:59
@jimmycheng603 for your second question, I think your questions is that whether each project need its own smv-jupyter session. If so, the answer is yes. Currently smv-jupyter and smv-pyshell etc. only support a single project `SmvApp` instance. We don't have a clear use case which need a single smv-jupyter session to support multiple projects yet. If you have one, please share, so that we can discuss whether the use case can be addressed by current scripts, or we need something new.

**Comment by laneb** [comment] 2017-08-02 22:13
Is anything else needed on this issue?

**Comment by jimmycheng603** [comment] 2017-08-03 02:17
tks, I have nothing else about this issue right now. in addtion, does smv support udf , I want to use the hive function of last_day  to smv

**Comment by AliTajeldin** [comment] 2017-08-03 18:56
@jimmycheng603 I'll go ahead and close this ticket then.  If you any other issues, please open a ticket for those specific issues or questions.

**Closed by AliTajeldin** 2017-08-03 18:56 UTC
Labels: bug
