### ISSUE TITLE
class defined in project core cannot be resolved

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#346] opened 2016-08-19 19:28 UTC
In project core, define a class such as below:
```
  class SampleOf(val ds: SmvDataSet, key: String,
    rate: Double = 0.01, partition: Int = 64) extends SmvModule(s"Sample of ${ds.name}") {
    override def requiresDS = Seq(ds)
    override def run(i: runParams) = {
      val df = i(ds)
      df.smvHashSample(df(key), rate).repartition(partition)
    }
  }
```

In another stage, use above class:
`object SampleDF extends SampleOf(DF, "ID", 0.01, 64) with SmvOuput`

When trying to resolve SampleDF, get below error:
_java.lang.IllegalArgumentException: invalid class name for crc: com.twineanalytics.neodm.core.SampleOf
        at org.tresamigos.smv.ClassCRC$.org$tresamigos$smv$ClassCRC$$step(ClassCRC.scala:77)
        at org.tresamigos.smv.ClassCRC$$anonfun$checksum$1.apply(ClassCRC.scala:66)
        at org.tresamigos.smv.ClassCRC$$anonfun$checksum$1.apply(ClassCRC.scala:66)
......_

**Comment by Kai-Chen** [comment] 2016-08-22 21:19
This is caused by the offending class being inside a `package object`, which results in name mangling of the class (being named `package$<classname>`.  Fixed by moving the SmvModule classes outside the `package object`.

**Closed** 2016-08-23 18:21 UTC
