### ISSUE TITLE
DataSet MetaData Strategy

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#332] opened 2016-07-26 23:57 UTC
## Motivation

With the completion of issue #324 we can now programatically add descriptions to dataset.s  However, the descriptions consist of free text, and as we've experienced, some of them would have `#` and also url links such as `http://` in them.  And since both `#` and `//` are treated as the start of a comment in the schema file, the description text following these characters would be truncated, leaving the JSON representation unclosed.

This problem leads us to reconsider the option of saving meta data apart from the schema file and potentially replacing it for non-csv formats.
## Format of the `.meta` File

The `.meta` file will contain a JSON object, with the following attributes):

| Key | Value |
| --- | --- |
| smvDesc | Array of columnName -> columnDescription |

We can extend with additional attributes for other meta information.
### Example

``` javascript
{
  "smvDesc" : [
    { "columnName" : "Medical_Blah_Blah_Blah", "columnDescription": "This is something that nobody would care but is actually very important '#'; for additional information see https://somewhere.obscure.net/deep/learning/corner" },
    { "columnName": "A", "columnDescription": "B" }
    ]
  }
}
```
## Overriding

There can be project-level and dataset-level meta data, all stored with the same format.  A dataset-level meta file will be merged with the project-level meta file, if one is available, before it is applied to the dataset.

When persisting a dataset, the `.meta` file will contain the merged meta data from both the project and the dataset.  When reading a dataset, the meta content from the `.meta` file will be merged with the project meta, with the more specific (dataset) overriding the more general (project).
## Related Issues
- #238 
- #121 

cc @ninjapapa @AliTajeldin

**Comment by AliTajeldin** [comment] 2016-07-30 04:06
I have a couple of questions about the file format:
* Would the above be repeated for each attribute?  That is, what if I have another column attribute for label?  Would I then have to create another top level entry "smvLabel" and list all the columns again with their name and label?  Or are we expecting "smvDesc" to be the top level for all column info (in which case we need to rename to something like "columns").
* Can we remove the world "column" from all the keys.  Seems redundant.
* Where should dataset level meta info go?  How about a top level "dataset" section?

Perhaps something like:
```json
{
  "dataset" : {
    "created-by" : "Bob",
    "has-header" : true,
    "..." : "..."
  },

  "columns" : [
    {
      "name" : "UserName",
      "type" : "Integer",
      "description": "This is where the real user name goes",
      "labels" : ["A", "B", "C"],
      "..." : "..."
    },
    {
      "name" : "Adress",
      "..." : "..."
    },
  ]
}
```

**Comment by Kai-Chen** [comment] 2016-07-31 21:18
Yes I like this :+1:

**Comment by AliTajeldin** [comment] 2017-04-17 21:21
Closing as duplicate of #121.  All work on meta data should be tracked on the other ticket.

**Closed by AliTajeldin** 2017-04-17 21:21 UTC
