### ISSUE TITLE
Slight Modification on the SMV Quick Start tutorial #1

### ISSUE THREAD

**Issue by tianruiwang** [TresAmigosSD/SMV#777] opened 2017-05-17 21:44 UTC
In the SMV quick start "run example app" section, the command "smv-pyrun --run-app" should be run in the project directory ("MyApp"), which is not mentioned in the tutorial.

**Comment by laneb** [comment] 2017-06-01 01:41
Closing as duplicate of #775.

**Closed by laneb** 2017-06-01 01:41 UTC
