### ISSUE TITLE
Install instructions do not work when the -spark flag is not included

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#846] opened 2017-06-01 08:36 UTC
Instructions [here](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_install.md#install-smv-using-curl) seem to be out of sync.... We already have Spark. The alternative of building SMV from source just to get the JAR is far from ideal

**Comment by laneb** [comment] 2017-06-01 09:38
This is a bug in the script's option parsing. Must've made a mistake when resolving a merge conflict.

**Comment by laneb** [comment] 2017-06-01 09:41
The problem is fixed on master. @AliTajeldin my apologies but I think we will need to do another release (or rerelease 1.5.2.10) promptly to fix this.

**Comment by laneb** [comment] 2017-06-14 01:13
Fixed with release 1.5.2.11.

**Closed by laneb** 2017-06-14 01:13 UTC
