### ISSUE TITLE
release 1.5.2.11 python api doc is brocken

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#892] opened 2017-06-16 00:03 UTC
The Python API only has toc but no real content.

**Comment by AliTajeldin** [comment] 2017-06-16 01:13
Set the link back to 1.5.2.10 for now until the problem is fixed in #882

**Comment by AliTajeldin** [comment] 2017-06-16 02:03
Fixed 1.5.2.11 and fixed the "\r" issue in `smv-release` (see #882)

**Closed by AliTajeldin** 2017-06-16 02:03 UTC
