### ISSUE TITLE
Enhance error message on Python side

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#479] opened 2017-02-17 01:41 UTC
The following error message (or similar) happens when SMV module fails for a lot different types of reasons, which makes it not very helpful for developer. 

```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-1-f76100db3732> in <module>()
----> 1 store_counts = pdf(".....reg_price.JoinReg")
/home/net1/robja001/local/SMV/python/smvshell.pyc in <lambda>(fqn)
     17 jvmShellCmd = smvPy._jvm.org.tresamigos.smv.shell.ShellCmd
     18
---> 19 pdf = lambda fqn: smvPy.runModule(fqn)
     20 ddf = lambda fqn: smvPy.runDynamicModule(fqn)
     21 openHive = lambda tableName: DataFrame(jvmShellCmd.openHive(tableName)                                   , smvPy.sqlContext)
/home/net1/robja001/local/SMV/python/smv.pyc in runModule(self, fqn)
    220         """Runs either a Scala or a Python SmvModule by its Fully Qual                                   ified Name(fqn)
    221         """
--> 222         jdf = self.j_smvPyClient.runModule(fqn)
    223         return DataFrame(jdf, self.sqlContext)
    224
/home/net1/robja001/local/spark-1.5.2-bin-hadoop2.6/python/lib/py4j-0.8.2.1-sr                                   c.zip/py4j/java_gateway.py in __call__(self, *args)
    536         answer = self.gateway_client.send_command(command)
    537         return_value = get_return_value(answer, self.gateway_client,
--> 538                 self.target_id, self.name)
    539
    540         for temp_arg in temp_args:
/home/net1/robja001/local/spark-1.5.2-bin-hadoop2.6/python/pyspark/sql/utils.p                                   yc in deco(*a, **kw)
     34     def deco(*a, **kw):
     35         try:
---> 36             return f(*a, **kw)
     37         except py4j.protocol.Py4JJavaError as e:
     38             s = e.java_exception.toString()
/home/net1/robja001/local/spark-1.5.2-bin-hadoop2.6/python/lib/py4j-0.8.2.1-sr                                   c.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id,                                    name)
    298                 raise Py4JJavaError(
    299                     'An error occurred while calling {0}{1}{2}.\n'.
--> 300                     format(target_id, '.', name), value)
    301             else:
    302                 raise Py4JError(
Py4JJavaError: An error occurred while calling o33.runModule.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Mess                                   age: x
        at py4j.Protocol.getReturnValue(Protocol.java:417)
        at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:1                                   13)
        at com.sun.proxy.$Proxy53.getDataFrame(Unknown Source)
        at org.tresamigos.smv.SmvExtModule.run(SmvDataSet.scala:577)
        at org.tresamigos.smv.SmvModule.doRun(SmvDataSet.scala:453)
        at org.tresamigos.smv.SmvDataSet$$anonfun$computeRDD$1.applyOrElse(Smv                                   DataSet.scala:207)
        at org.tresamigos.smv.SmvDataSet$$anonfun$computeRDD$1.applyOrElse(Smv                                   DataSet.scala:206)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction                                   .scala:33)
        at scala.util.Failure.recoverWith(Try.scala:172)
        at org.tresamigos.smv.SmvDataSet.computeRDD(SmvDataSet.scala:206)
        at org.tresamigos.smv.SmvDataSet.rdd(SmvDataSet.scala:139)
        at org.tresamigos.smv.SmvApp.resolveRDD(SmvApp.scala:188)
        at org.tresamigos.smv.SmvApp.runModule(SmvApp.scala:417)
        at org.tresamigos.smv.python.SmvPyClient.runModule(SmvPythonProxy.scal                                   a:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImp                                   l.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcc                                   essorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133                                   )
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:207)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by AliTajeldin** [comment] 2017-02-17 18:49
@laneb : As discussed yesterday, let's do a quick fix for this on master rather than wait for the big refactor.  Let's create a simple "error" that is not caught by the compiler and reproduce the cryptic message first.  Hopefully, this is as simple as putting a try/catch around the run call on the python side.

**Comment by laneb** [comment] 2017-02-17 22:05
Any error raised by the `requiresDS` or `run` methods of any `SmvPyDataSet` should now print the Python stack trace for the error. This was accomplished essentially by wrapping the callback's entrypoints to `SmvPyDataset` (`dependencies` and `getDataFrame`) with a try/except block that prints the trace explicitly. The full stack trace for such an error will now look something like 

```
Traceback (most recent call last):
  File "/Users/laneb/twine/SMV/python/smv.py", line 407, in dependencies
    arr = smv_copy_array(self.smvPy.sc, *[x.urn() for x in self.requiresDS()])
  File "/Users/laneb/twine/MyApp/src/main/python/org/tresamigos/myapp/stage1/employment.py", line 22, in requiresDS
    return [Employmen]
NameError: global name 'Employmen' is not defined
Traceback (most recent call last):
  File "/Users/laneb/twine/SMV/tools/../python/smvapp.py", line 28, in <module>
    smvPy.j_smvApp.run()
  File "/Users/laneb/Library/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/Users/laneb/Library/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
  File "/Users/laneb/Library/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o23.run.
: py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:417)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
	at com.sun.proxy.$Proxy26.dependencies(Unknown Source)
	at org.tresamigos.smv.SmvExtModule.requiresDS(SmvDataSet.scala:590)
	at org.tresamigos.smv.SmvDataSet.resolvedRequiresDS$lzycompute(SmvDataSet.scala:63)
	at org.tresamigos.smv.SmvDataSet.resolvedRequiresDS(SmvDataSet.scala:63)
	at org.tresamigos.smv.SmvDataSet.allDeps(SmvDataSet.scala:70)
	at org.tresamigos.smv.SmvApp$$anonfun$18.apply(SmvApp.scala:594)
	at org.tresamigos.smv.SmvApp$$anonfun$18.apply(SmvApp.scala:594)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at org.tresamigos.smv.SmvApp.run(SmvApp.scala:594)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

A further enhancement will be to ensure that the 3 traces print in a more intuitive order, and perhaps even format them or space them out.

**Comment by laneb** [comment] 2017-02-18 03:23
A user defined module may have a runtime error (such as a `NameError` or `ImportError`) that occurs when the module itself imported. For example, the file might contain
```
import tracebak

module M(SmvPyModule)
... 
```
which would cause an `ImportError` due to inability to import the nonexistent (misspelled) package. This runtime error would be raised inside of `PythonDataSetRepository`'s `dsForName`. Probably, all module lookup errors should be printed explicitly. Additionally, they should probably cause `SmvApp` to exit - currently, `ImportError` is handled by `dsForName` in such a way that it does not cause `SmvApp` to exit, leading to poorly-defined behavior down the line.

**Comment by jacobdr** [comment] 2017-02-26 18:22
Just want to confirm the behavior change here. It seems like the commits in ce6944b and fb071cc call to the `print_exc` in the try-except blocks -- but then do not re-raise before returning, whereas they would silently raise in the initial implementation.

**Comment by laneb** [comment] 2017-02-26 18:58
This in fact did still raise an error, but not the right one. In any case, this has since been resolved. The most recent source reraises the error.

**Comment by laneb** [comment] 2017-03-07 23:11
Based in [https://github.com/bartdag/py4j/issues/137](this issue) from the Py4J repo there is the possibility for a more general solution, but it hasn't been implemented yet.

**Comment by laneb** [comment] 2017-05-25 19:45
Until such time as Py4j Solves this problem for us, the solution is to create a decorator for Python method implementing Py4j interfaces. Something like @SmvPy4jTraceback. There will need to be a mix-in class that implements this interface and a overrides the `__getattribute__` method to wrap decorated methods in the appropriate try/except.

**Comment by Khorkhe** [comment] 2017-05-31 23:14
fixed

**Closed by Khorkhe** 2017-05-31 23:14 UTC
Labels: high_p
