### ISSUE TITLE
changes in abstract class does not trigger re-run on derived class

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#642] opened 2017-04-18 22:00 UTC
when making changes on an abstract class SmvPyModule, df() on the derived class still use the previously persisted output, which does no reflect changes in the abstract class.

**Comment by AliTajeldin** [comment] 2017-04-19 00:33
@XiaosenChen : I think we confirmed that this is not related to abstract classes but rather creating a new module in an existing file will not be seen by `df()`.  Is that correct?

**Comment by XiaosenChen** [comment] 2017-04-19 00:48
that is in another issue just opened. This issue is actually about abstract
class.

**Comment by ninjapapa** [comment] 2017-04-19 16:40
The reason is that current datasetHash depends on the code of the sub class only. Need to trace up to the super class's code too.

**Comment by AliTajeldin** [comment] 2017-04-19 19:18
Marking this as a bug as we do actually walk the mro of the base class to compute the hash of the parent classes.  From `smvpydataset.py`:
```python
            for m in inspect.getmro(cls):
                try:
                    if m.IsSmvPyDataSet and m != cls and not m.fqn().startswith("smv."):
                        res += m(self.smvApp).datasetHash()
                except: pass
```

Note that we do instantiate the parent class with `smvApp` instance injected (`m(self.smvApp)` in above code snippet).  So the parent class **MUST** have a constructor that accepts the single app argument for the parent hash to have an effect.
If that is the case, then we should probably fail loudly rather than just pass and ignore the parent hash.

**Comment by laneb** [comment] 2017-04-19 21:19
A suggestion from @AliTajeldin is to separate out a `classHash` class method of `SmvDataSet`, and when iterating the MRO in an instance's `datasetHash` (perhaps renamed `instanceHash`) we only call the superclasses' `classHash`, since this is the only information we need. This will work around issues related to ABCs that we can't instantiate.

**Comment by laneb** [comment] 2017-04-19 23:07
I think there is another complication, though. If the ABC `foo` is defined in file `f1` and the implementation `bar` is defined in different file `f2`, then we won't reload `foo` when reload `bar` because the reload of `bar` only recompiles `f2`.

**Comment by laneb** [comment] 2017-04-24 19:11
I will make a pull request soon that fixes the issue of making sure ABCs are reloaded. Then I will proceed with the described fix for the problem that `datasetHash` is failing because we can't instantiate ABCs.

**Comment by laneb** [comment] 2017-04-24 19:11
(close was an accident)

**Comment by laneb** [comment] 2017-04-26 02:02
The issue of making sure ABCs reload is fixed. User-defined constructors for `SmvModules` will remain unsupported for now - @AliTajeldin will update the ABC example to reflect this.

**Closed by laneb** 2017-04-26 02:02 UTC
Labels: bug, high_p

**Comment by jacobdr** [comment] 2017-04-26 02:13
Do we actually have an ABC example somewhere? Tried to use Github search to find it, but to no avail

**Comment by AliTajeldin** [comment] 2017-04-26 22:00
@jacobdr created #682 to add an example.
