### ISSUE TITLE
Need to use Spark native read and write for data file persisting 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#431] opened 2016-11-26 02:42 UTC
It sounds like in Spark 1.5 the `map` method (which call `rdd` method) on DataFrame is actually an action. In sounds like the `map` step and the `saveAsTextFile` step are 2 actions in the FileIOHandler. It's likely to run out of memory on executers. 

It was not a problem before 1.3, since by them DF IS a RDD. It may not be a problem after 2.0 (not sure). Anyhow, we should move forward to use Spark's native reader and writer for persisting.

**Comment by ninjapapa** [comment] 2016-11-27 22:12
Noticed that even use native writer in 1.5, map and save are 2 steps. No urgency of making our persist using native writer.

**Comment by Khorkhe** [comment] 2017-05-23 00:40
is this a duplicate of #153 ?

**Comment by AliTajeldin** [comment] 2017-05-23 21:35
Yup.  closing as dup of #153.

**Closed by AliTajeldin** 2017-05-23 21:35 UTC
Labels: duplicate
