### ISSUE TITLE
Shift default build method from Maven to SBT

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#297] opened 2016-03-18 23:35 UTC
So far SBT build worked just as good as Maven. Given the simplicity of SBT compare to Maven, we should consider to shift to SBT totally.

**Comment by xuxiaoshun** [comment] 2016-03-18 23:40
We can refer to the options of building spark:
"Maven is the official build tool recommended for packaging Spark, and is the build of reference. But SBT is supported for day-to-day development since it can provide much faster iterative compilation. More advanced developers may wish to use SBT."
- from http://spark.apache.org/docs/latest/building-spark.html#building-with-sbt

**Comment by Kai-Chen** [comment] 2016-05-22 21:34
In ClassCRCTest, there are now 4 tests that compile Scala code during test and load them with a custom classloader to check that the hash-of-hash is compliant to the spec.  These only work in SBT and doesn't work with Maven's Scala plugin because the plugin uses an incompatible scala-reflect jar.  The tests are currently `ignore`d to ensure maven can continue to build.

**Comment by AliTajeldin** [comment] 2017-03-11 03:18
Closing as duplicate of #464

**Closed by AliTajeldin** 2017-03-11 03:18 UTC
