### ISSUE TITLE
Memory leaks in sbt test

### ISSUE THREAD

**Issue by hubertp-lshift** [TresAmigosSD/SMV#588] opened 2017-04-04 09:01 UTC
Running `test` continuously in the sbt console (not cold runs) will lead to OutOfMemory exceptions in Metaspace (heap is good).  This is for 2.1 branch

**Comment by hubertp-lshift** [comment] 2017-04-04 09:31
Also the number of threads used just keeps on growing. Probably something is not shutdown correctly.

**Comment by hubertp-lshift** [comment] 2017-04-05 11:19
https://github.com/TresAmigosSD/SMV/pull/591

**Comment by AliTajeldin** [comment] 2017-04-05 23:29
merged.

**Comment by Kai-Chen** [comment] 2017-04-12 07:15
The issue with running out of metaspace is not limited to the 2.1 branch but is also manifest in the master branch as well.

Forking tests does avoid this.
However, it introduces a significant increase in time when tests are run.
The original intention of using a single SparkContext in a single `test` run is so that we can avoid the cost of creating it for each test and can run the complete suite quickly.

On my machine, tests finish running in just over 1 minute.
That's before this change.
When I run tests from the 2.1 tip now, it takes almost 4 minutes for the tests to finish.
Furthermore, quite a few tests could not complete, and the `test` task fails, because derby opens too many files -- possibly because the forked tests are not being shut down cleanly.

Running `test` from the console multiple times is a developer task; whereas running `sbt test` once and check for error is a CI task, which takes precedence.
You can also add the following to your `sbtopt` file to increase the memory allocated to sbt so you can run `test` a few more times before you need to exit the sbt console.
```
# set memory options
#
#-mem   <integer>  
-mem 2048
```

Based on the above, I'd like to revert the committed changes, with the above work-around for developers.

**Comment by hubertp-lshift** [comment] 2017-04-12 08:51
To be fair, I don't think requiring 2GB for metaspace is a reasonable thing to do. Heap maybe, but metaspace, not really. 
There are two issues here: 1) the change forked tests in order to mitigate memory issues 2) the commit changed the way spark is started; it is restarted for the new test suite, not for every single test.

I do think there is an underlying problem somewhere with Spark/Hive which leads to memory leaks but that's outside of the scope of this bug.
Asking a developer to kill sbt every few times is even more annoying than just waiting for tests to pass. Everyone is forking Spark tests to mitigate memory issues, but when it comes to restarting Spark the schools are different, so that's where there is potentially a room for improvement if time is of essence. Finally, CI running 4 minutes for tests is completely fine, IMHO.

**Comment by AliTajeldin** [comment] 2017-04-12 19:24
@hubertp-lshift : Is there a way to combine suites in a single fork to reduce number of spark instances created?  That would be the best of both worlds.
@Kai-Chen : I'm not as concerned about the 1 vs 4 minutes test run as I'm about failing test cases due to derby.  Are those errors reproducible or spurious?  I would imagine with forked processes, all the resources would have been automagically cleaned up by OS on ext.

**Comment by Kai-Chen** [comment] 2017-04-12 19:42
It is reproducible on my machine.
Not really an artifact of forking, I think, but probably because of the new method of starting and shutting down Spark and HiveContext.

Here's an abbreviated error trace:

> Caused by: java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:derby:;databaseName=/tmp/spark-f3a225df-f688-4f33-9b6b-e5b683ebdba4/metastore;create=true, username = APP. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
> java.sql.SQLException: Failed to create database '/tmp/spark-f3a225df-f688-4f33-9b6b-
> e5b683ebdba4/metastore', see the next exception for details.
> ...
> Caused by: java.sql.SQLException: Failed to create database '/tmp/spark-f3a225df-f688-4f33-9b6b-e5b683ebdba4/metastore', see the next exception for details.
> 
> 
> ...
> Caused by: java.sql.SQLException: Exception during creation of file /tmp/spark-f3a225df-f688-4f33-9b6b-e5b683ebdba4/metastore/seg0/c150.dat for container
> ...
> Caused by: java.io.FileNotFoundException: /tmp/spark-f3a225df-f688-4f33-9b6b-e5b683ebdba4/metastore/seg0/c150.dat (Too many open files)
> ...
>

**Comment by Kai-Chen** [comment] 2017-04-12 19:54
Just some information on the sbt mem setting.
SBT by default uses only 1G, and that's for the whole JVM.
The `mem` setting is for the whole JVM as well, not just for the metaspace, although the metaspace is supposed to expand dynamically.
So you can see doubling it to 2G is not a big deal.
Setting it higher will certainly buy you a lot more time.

Another way is to `fork` for `testOnly`, since that's what gets run most often.
That will allow you to keep a long running sbt while developing and also get faster response when you need to do a quick sanity check for the project.

**Comment by hubertp-lshift** [comment] 2017-04-13 08:22
That's weird, I didn't get those derby errors.

**Comment by AliTajeldin** [comment] 2017-04-13 19:46
Is there any way to parameterize the fork/no-fork so that users can choose to either run `sbt test` without fork when just doing code check-in and enable fork for long running `~test` tasks?  Perhaps even add a new sbt task `fork-test` or something along that line?

**Comment by AliTajeldin** [comment] 2018-10-29 19:56
Will close as we reduced the number of SBT test considerably.

**Closed by AliTajeldin** 2018-10-29 19:56 UTC
Labels: bug, high_p
