### ISSUE TITLE
No error message when trying to run module with csv.lock file present

### ISSUE THREAD

**Issue by ktlu4** [TresAmigosSD/SMV#955] opened 2017-08-09 22:55 UTC
Would be helpful to have an alert in this situation showing that a csv.lock file is preventing the module from running.

**Comment by laneb** [comment] 2017-08-10 00:16
In what situation would your csv file would be locked? Also, what happens in that situation today - I assume an opaque error message is thrown?

**Comment by laneb** [comment] 2017-08-10 00:18
I forgot we added that `SmvLock` stuff. I presume the file being locked by SMV?

**Comment by laneb** [comment] 2017-08-10 18:33
After discussing with @ktlu4, the issue is that it would be helpful if a message was printed to alert you when a job is waiting for a locked file to be freed.

**Comment by AliTajeldin** [comment] 2017-08-10 20:50
How would we distinguish a legitimate lock from one left behind from a killed job?

**Comment by Kai-Chen** [comment] 2017-10-06 00:02
> How would we distinguish a legitimate lock from one left behind from a killed job?

I don't think there is a way from within a running SmvApp instance itself.

There are some choices in generating diagnostic messages:
1. We could scan the output directory at the start of SmvApp and report all the existing module-level lock files.
This would help the user to diagnose any possible problems.
We shouldn't automatically remove any lock files that we find, because there could be another SmvApp process running that needs the lock file for the module.
Presumably the user should know if it's safe to remove it.
1. We could also print a message every time we fail to obtain the lock (either because another process is computing the same module or because a previous computation job was killed and the lock file got left behind)

And we could have a separate tool|script that report and|or clean up any dangling lock files.

Another way to approach this is to use `Runtime.addShutdownHook` to register a clean-up procedure, and have SmvLock add and remove the lock file path each time it acquires and release the lock.
That should ensure, in theory at least, that, even if the JVM process is killed, we will not leave any dangling lock file behind.

@AliTajeldin Please advise which of the above suggestions to implement, or if there is another better way.

**Comment by AliTajeldin** [comment] 2017-10-06 00:14
@Kai-Chen Let's discuss next time you are in office.  The above solutions would work for a single user instance of spark but I fell will have issues when multiple users share the same output directory.

**Comment by Kai-Chen** [comment] 2017-10-09 21:44
Per discussion, this situation will be difficult to resolve in code, and we will take the approach to add diagnostic messages to help the user to detect and resolve the problem.

All the following will be implemented:
1. Use `addShutdownHook` to manage any dangling lock files if the JVM is shutdown by a signal.
1. The first time when a module fails to obtain the computation lock, it should print to `stdout` a message about waiting for the lock, including how long it has been since the lock was created
1. In `get_dataset_info` return additional information about whether the lock is present and when the lock was created

**Comment by Kai-Chen** [comment] 2017-10-24 23:26
For item 3 in the above list, we will need to expose a method in `SmvApp` to return the lockfile status of a given module (in Python or Scala).
This should be ordinary, except that currently, in `get_dataset_info` we make a call to get a Python SmvDataSet and fill out a thin value class for UI.
The call to SmvApp would mean that we are going to a second place for a missing piece of information.

I don't mind it that much, but have a feeling that you @AliTajeldin may think otherwise.

**Comment by laneb** [comment] 2018-02-02 06:32
What is the status of this work?

**Comment by Kai-Chen** [comment] 2018-02-02 17:39
It's on hold as we haven't arrived at a solution wrt how to display the lock file status in the UI.

**Comment by laneb** [comment] 2018-02-02 23:46
Ok. Yesterday we were pulling hair out over a job that kept hanging, and it
turned out that it was due to a dangling lockfile. It is not uncommon on
this cluster for jobs to be killed externally, and I was able to reproduce
the problem by getting my job killed not much later. A notification about
the lock would have saved us quite a bit of time. Perhaps we can merge that
part of the work while the remainder is delayed? Or is that what you mean
by UI?

**Comment by Kai-Chen** [comment] 2018-02-03 01:14
Yes absolutely.
I will submit a PR right now.

@AliTajeldin do you think we need to give the UI part of this ticket a higher priority, perhaps?

**Comment by AliTajeldin** [comment] 2018-02-05 19:58
@Kai-Chen not sure what you mean by UI part.  Atlas?

**Comment by Kai-Chen** [comment] 2018-02-05 20:13
Yes, atlas.

**Comment by AliTajeldin** [comment] 2018-02-06 01:51
Let's make that a separate ticket and close this and delete any branch associated with it.

**Closed** 2018-02-06 02:06 UTC
