### ISSUE TITLE
Can run custom script with `smv-run`

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#1165] opened 2018-03-12 05:46 UTC
Add an option to `smv-run` to specify a custom script to run, instead of running the default `runapp.py`.

It is assumed that the custom script itself will handle the start of SmvApp.

**Comment by AliTajeldin** [comment] 2018-03-13 03:48
Duplicate of #1132

**Closed by AliTajeldin** 2018-03-13 03:48 UTC
