### ISSUE TITLE
Switch python version caused an error when run smv-pyshell or smv-jupyter

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#886] opened 2017-06-14 00:16 UTC
We store previous command history in `~/,pysparkhistory` and try to read it to readline when start pyshell. When python version changes, the format of the history file changes, so reading it back in will fail, which causes a error in smv-jupyter without pointing to the correct place, so very hard to debug.

We need to use try and catch in `smv_pyshell_init.py.template` when loading the history.

**Comment by laneb** [comment] 2017-06-14 03:56
I am actually having trouble running `smv-pyshell` with Python 3, apparently due to [this issue](https://github.com/apache/spark/pull/10255) which was fixed in Spark 1.6. Which Spark are you running against?

**Comment by ninjapapa** [comment] 2017-06-14 04:55
I was using Spark 1.5.2.

**Comment by laneb** [comment] 2017-06-14 19:41
Per conversation with @ninjapapa, the issue may be from switching between minor version of Python 2, but not sure. Setting aside the issues with running pyspark 1.5.2 with Python 3, it is also conceivable that there would be an issue to do with default character encoding in Python 3 (utf8) vs Python 2 (ascii). Will be difficult to replicate without knowing which Python versions were involved.

**Comment by laneb** [comment] 2017-06-14 20:07
I have run into an issue with a corrupted pyspark history file in the past, although I don't think it was Python version related. We should just try to read the file and ignore it if we are unable to read it.

**Comment by Khorkhe** [comment] 2017-06-20 05:41
After commit, history still works locally in smv-pyshell, but not sure how to verify that this issue was resolved, as Lane and I were unable to reproduce it locally.

I suppose one way could be to try this branch (i886) on the machine that was initially affected, though I'm not entirely satisfied with this solution.  Any suggestions?

**Comment by AliTajeldin** [comment] 2017-06-20 07:07
Can we just manually corrupt the history file to see if we can reproduce the error and then fix the import of history to ignore errors (is that even possible?)

**Comment by Khorkhe** [comment] 2017-06-20 07:27
That may reproduce the error but not the behavior though, right? Feels like this issue should be two separate issues maybe.

**Comment by ninjapapa** [comment] 2017-06-20 15:35
No need to over complicated this. We don't need to know how the history file get corrupted. The history there is just to access command one typed in previously. There is no big issue even if we removed a history file accidentally.

**Comment by ninjapapa** [comment] 2017-06-20 15:42
Need to delete the history file if try failed.

**Comment by laneb** [comment] 2017-06-20 20:24
FWIW, if we were to identify the source of the 'corruption' we might be able to recover the history instead of deleting it (e.g. if it's a version-related encoding issue).

**Closed** 2017-06-20 21:12 UTC

**Comment by ninjapapa** [comment] 2017-06-20 21:22
Since we are moving to using Jupyter as the interactive shell instead of the raw Python shell, we don't need to put too much effort to optimize how to handle a rare case on a tool which is mainly for fallback. 
It was an issue, because the corrupted history preventing the shell to start, which made SMV unusable. As the history get deleted, the only issue left is that the old history is not there anymore, which should not be a big issue when user playing with their environment.
