### ISSUE TITLE
Generate Python API document

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#378] opened 2016-09-25 14:48 UTC
Need to create Python API doc and make it part of the 'site' build.

**Comment by Kai-Chen** [comment] 2016-10-01 17:37
Should implement this first as an SBT task, and then migrate the `site` build to SBT to complete the transition from maven.

**Comment by AliTajeldin** [comment] 2017-02-11 04:20
Given the decision to emphasize the python interface, we should abandon the effort to create a single API doc in scala that is then translated into the python doc.  Going forward, we will probably create the helpers in python directly anyway.   Instead we should document the python API in python directly.

Investigate use of either [pydoc](https://docs.python.org/2/library/pydoc.html) or [sphinx](http://www.sphinx-doc.org/en/stable/).  In the ideal case, the API documentation should be close to the API definition rather than in a separate "book".

**Comment by AliTajeldin** [comment] 2017-04-02 00:56
closing this as duplicate of #576 .  The other ticket has all the check-ins associated with it.

**Closed by AliTajeldin** 2017-04-02 00:56 UTC
Labels: high_p
