### ISSUE TITLE
Remove pyc files when rebuild

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#596] opened 2017-04-05 16:48 UTC
When SMV has updates, user typically do a `git pull` and then run `sbt assembly` to create the SMV fat jar for their (python) projects to use. 

Sometimes there are leftover `*.pyc` files, which somehow are not recompiled when run projects. It's better to clean up, such as run `find ./ -name *.pyc -exec rm {} \;` as the last step of the `sbt assembly`.

**Comment by laneb** [comment] 2017-04-05 18:32
If you can consistently duplicate Python not recompiling project code, I would be very curious to see. We don't create the `assembly` task ourselves, but I think there is a way in add an additional step to the beginning of an existing task. If not, maybe we can create a separate task for removing the `.pyc` files and add it as a dependency of `assembly`.

**Comment by laneb** [comment] 2017-04-08 00:12
Haven't seen the situation that Python won't recompile code, but I *did* run into a very similar scenario today. On master, I was trying to run tests and was getting a strange `ImportError` (cannot import `SparkSession`) from `src/main/smv/smvpy.py`, when there was no `src/main/smv/smvpy.py` in that branch. But it turned out I did have `src/main/smv/smvpy.pyc`, most likely leftover from checking out the 2.1 branch at some previous point. Deleting `src/main/smv/smvpy.pyc` fixed the problem.

**Comment by AliTajeldin** [comment] 2017-04-09 23:07
closing as duplicate of #612 as the other has a good description on how to replicate.

**Closed by AliTajeldin** 2017-04-09 23:07 UTC
